name: Release theme packages
run-name: Releasing ${{github.ref_name}}

on:
  # Trigger after pushing a version tag.
  push:
    tags:
      - 'v[0-9].**'
  # Trigger manually.
  workflow_dispatch:

jobs:
  build:
    name: Build themes
    runs-on: ubuntu-24.04
    env:
      TAG_NAME: ${{github.ref_name}}
    steps:
      - name: Install jsonnet
        run: |
          sudo apt-get update
          sudo apt-get install -y jsonnet
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: make

      # Prepare packages
      - run: mkdir -p dist
      - name: Prepare VSCode package
        uses: lannonbr/vsce-action@4.0.0
        with:
          args: 'package --out dist'
      - name: Prepare Sublime Text package
        run: |
          zip -j "dist/evolved-theme-${TAG_NAME}.sublime-package" sublime-text/*.sublime-color-scheme

      # Upload artifacts
      - name: Upload iTerm2 themes
        uses: actions/upload-artifact@v4
        with:
          name: iterm2
          path: iterm2/*.itermcolors
      - name: Upload Sublime Text themes
        uses: actions/upload-artifact@v4
        with:
          name: sublime-text
          path: dist/*.sublime-package
      - name: Upload VSCode themes
        uses: actions/upload-artifact@v4
        with:
          name: vscode
          path: dist/*.vsix

